import { CourseData } from './types'

export const courseData: CourseData = {
  5: {
    id: 5,
    label: '5 сынып',
    topics: [
      {
        id: 'natural-numbers',
        title: 'Натурал сандар',
        description: 'Натурал сандармен амалдар, бөлгіштік белгілері',
        questions: [
          {
            id: '5-nat-1',
            type: 'single',
            question: '245 + 378 қосындысын табыңыз',
            options: ['613', '623', '633', '523'],
            correctAnswer: '623',
            explanation: '245 + 378 = 623',
            points: 1,
          },
          {
            id: '5-nat-2',
            type: 'single',
            question: '1000 - 456 айырмасын табыңыз',
            options: ['544', '554', '454', '444'],
            correctAnswer: '544',
            explanation: '1000 - 456 = 544',
            points: 1,
          },
          {
            id: '5-nat-3',
            type: 'input',
            question: '25 × 4 көбейтіндісін есептеңіз',
            correctAnswer: '100',
            explanation: '25 × 4 = 100',
            points: 2,
          },
          {
            id: '5-nat-4',
            type: 'multiple',
            question: '36 санының бөлгіштерін таңдаңыз',
            options: ['1', '2', '3', '4', '5', '6', '7', '9'],
            correctAnswer: ['1', '2', '3', '4', '6', '9'],
            explanation: '36 = 1×36 = 2×18 = 3×12 = 4×9 = 6×6',
            points: 2,
          },
          {
            id: '5-nat-5',
            type: 'single',
            question: '144 ÷ 12 бөліндісін табыңыз',
            options: ['10', '11', '12', '13'],
            correctAnswer: '12',
            explanation: '144 ÷ 12 = 12',
            points: 1,
          },
        ],
      },
      {
        id: 'fractions',
        title: 'Жай бөлшектер',
        description: 'Жай бөлшектерді салыстыру және амалдар',
        questions: [
          {
            id: '5-frac-1',
            type: 'single',
            question: '1/2 + 1/4 қосындысын табыңыз',
            options: ['1/6', '2/6', '3/4', '1/4'],
            correctAnswer: '3/4',
            explanation: '1/2 + 1/4 = 2/4 + 1/4 = 3/4',
            points: 1,
          },
          {
            id: '5-frac-2',
            type: 'single',
            question: 'Қай бөлшек үлкен: 2/3 немесе 3/5?',
            options: ['2/3', '3/5', 'Тең', 'Анықтау мүмкін емес'],
            correctAnswer: '2/3',
            explanation: '2/3 = 10/15, 3/5 = 9/15, демек 2/3 > 3/5',
            points: 1,
          },
          {
            id: '5-frac-3',
            type: 'input',
            question: '3/4 бөлшегін пайызбен көрсетіңіз (тек санды жазыңыз)',
            correctAnswer: '75',
            explanation: '3/4 = 0.75 = 75%',
            points: 2,
          },
        ],
      },
      {
        id: 'geometry-basics',
        title: 'Геометрия негіздері',
        description: 'Периметр және аудан',
        questions: [
          {
            id: '5-geo-1',
            type: 'single',
            question: 'Қабырғасы 5 см болатын квадраттың периметрі қандай?',
            options: ['15 см', '20 см', '25 см', '10 см'],
            correctAnswer: '20 см',
            explanation: 'P = 4 × 5 = 20 см',
            points: 1,
          },
          {
            id: '5-geo-2',
            type: 'input',
            question: 'Ұзындығы 8 см, ені 5 см тіктөртбұрыштың ауданы неше см²?',
            correctAnswer: '40',
            explanation: 'S = 8 × 5 = 40 см²',
            points: 2,
          },
        ],
      },
    ],
  },
  6: {
    id: 6,
    label: '6 сынып',
    topics: [
      {
        id: 'divisibility',
        title: 'Бөлінгіштік',
        description: 'ЕҮОБ және ЕКОЕ табу',
        questions: [
          {
            id: '6-div-1',
            type: 'single',
            question: '12 және 18 сандарының ЕҮОБ-ын табыңыз',
            options: ['2', '3', '6', '12'],
            correctAnswer: '6',
            explanation: '12 = 2² × 3, 18 = 2 × 3², ЕҮОБ = 2 × 3 = 6',
            points: 1,
          },
          {
            id: '6-div-2',
            type: 'input',
            question: '4 және 6 сандарының ЕКОЕ-сін табыңыз',
            correctAnswer: '12',
            explanation: 'ЕКОЕ(4, 6) = 12',
            points: 2,
          },
          {
            id: '6-div-3',
            type: 'multiple',
            question: '2-ге және 3-ке бөлінетін сандарды таңдаңыз',
            options: ['12', '15', '18', '24', '25', '30'],
            correctAnswer: ['12', '18', '24', '30'],
            explanation: '6-ға бөлінетін сандар: 12, 18, 24, 30',
            points: 2,
          },
        ],
      },
      {
        id: 'ratios',
        title: 'Қатынастар мен пропорциялар',
        description: 'Пропорция құру және шешу',
        questions: [
          {
            id: '6-ratio-1',
            type: 'single',
            question: '2:3 = x:12 пропорциясынан x-ті табыңыз',
            options: ['6', '8', '9', '4'],
            correctAnswer: '8',
            explanation: 'x = 2 × 12 ÷ 3 = 8',
            points: 1,
          },
          {
            id: '6-ratio-2',
            type: 'input',
            question: '60 санының 25%-ын табыңыз',
            correctAnswer: '15',
            explanation: '60 × 0.25 = 15',
            points: 2,
          },
        ],
      },
      {
        id: 'negative-numbers',
        title: 'Теріс сандар',
        description: 'Теріс сандармен амалдар',
        questions: [
          {
            id: '6-neg-1',
            type: 'single',
            question: '(-5) + (-3) нәтижесін табыңыз',
            options: ['-8', '-2', '8', '2'],
            correctAnswer: '-8',
            explanation: '(-5) + (-3) = -8',
            points: 1,
          },
          {
            id: '6-neg-2',
            type: 'single',
            question: '(-4) × (-6) көбейтіндісін табыңыз',
            options: ['-24', '24', '-10', '10'],
            correctAnswer: '24',
            explanation: 'Теріс × теріс = оң, (-4) × (-6) = 24',
            points: 1,
          },
          {
            id: '6-neg-3',
            type: 'input',
            question: '(-15) ÷ 3 бөліндісін табыңыз',
            correctAnswer: '-5',
            explanation: '(-15) ÷ 3 = -5',
            points: 2,
          },
        ],
      },
    ],
  },
  7: {
    id: 7,
    label: '7 сынып',
    topics: [
      {
        id: 'linear-equations',
        title: 'Сызықтық теңдеулер',
        description: 'Бір белгісізді сызықтық теңдеулер',
        questions: [
          {
            id: '7-lin-1',
            type: 'single',
            question: '2x + 5 = 13 теңдеуін шешіңіз',
            options: ['x = 3', 'x = 4', 'x = 5', 'x = 9'],
            correctAnswer: 'x = 4',
            explanation: '2x = 13 - 5 = 8, x = 4',
            points: 1,
          },
          {
            id: '7-lin-2',
            type: 'input',
            question: '3x - 7 = 2x + 5 теңдеуінің шешімін табыңыз (тек санды жазыңыз)',
            correctAnswer: '12',
            explanation: '3x - 2x = 5 + 7, x = 12',
            points: 2,
          },
          {
            id: '7-lin-3',
            type: 'single',
            question: '4(x - 2) = 20 теңдеуін шешіңіз',
            options: ['x = 5', 'x = 6', 'x = 7', 'x = 8'],
            correctAnswer: 'x = 7',
            explanation: 'x - 2 = 5, x = 7',
            points: 1,
          },
        ],
      },
      {
        id: 'functions',
        title: 'Функциялар',
        description: 'Сызықтық функция және графигі',
        questions: [
          {
            id: '7-func-1',
            type: 'single',
            question: 'y = 2x + 3 функциясында x = 4 болғанда y неге тең?',
            options: ['9', '10', '11', '12'],
            correctAnswer: '11',
            explanation: 'y = 2(4) + 3 = 8 + 3 = 11',
            points: 1,
          },
          {
            id: '7-func-2',
            type: 'input',
            question: 'y = 3x - 1 функциясының y осімен қиылысу нүктесінің y координатасы қандай?',
            correctAnswer: '-1',
            explanation: 'x = 0 болғанда y = -1',
            points: 2,
          },
        ],
      },
      {
        id: 'triangles',
        title: 'Үшбұрыштар',
        description: 'Үшбұрыш түрлері және қасиеттері',
        questions: [
          {
            id: '7-tri-1',
            type: 'single',
            question: 'Үшбұрыштың ішкі бұрыштарының қосындысы неге тең?',
            options: ['90°', '180°', '270°', '360°'],
            correctAnswer: '180°',
            explanation: 'Кез келген үшбұрыштың ішкі бұрыштарының қосындысы 180°',
            points: 1,
          },
          {
            id: '7-tri-2',
            type: 'multiple',
            question: 'Тең бүйірлі үшбұрыштың қасиеттерін таңдаңыз',
            options: [
              'Екі қабырғасы тең',
              'Барлық қабырғасы тең',
              'Табанындағы бұрыштары тең',
              'Барлық бұрышы 60°',
            ],
            correctAnswer: ['Екі қабырғасы тең', 'Табанындағы бұрыштары тең'],
            explanation: 'Тең бүйірлі үшбұрышта екі бүйір қабырғасы және табанындағы бұрыштары тең',
            points: 2,
          },
        ],
      },
    ],
  },
  8: {
    id: 8,
    label: '8 сынып',
    topics: [
      {
        id: 'quadratic-equations',
        title: 'Квадрат теңдеулер',
        description: 'Квадрат теңдеулерді шешу',
        questions: [
          {
            id: '8-quad-1',
            type: 'single',
            question: 'x² - 5x + 6 = 0 теңдеуінің түбірлерін табыңыз',
            options: ['x = 2, x = 3', 'x = 1, x = 6', 'x = -2, x = -3', 'x = 2, x = -3'],
            correctAnswer: 'x = 2, x = 3',
            explanation: '(x - 2)(x - 3) = 0, x = 2 немесе x = 3',
            points: 1,
          },
          {
            id: '8-quad-2',
            type: 'input',
            question: 'x² = 49 теңдеуінің оң түбірін жазыңыз',
            correctAnswer: '7',
            explanation: 'x = ±7, оң түбір = 7',
            points: 2,
          },
          {
            id: '8-quad-3',
            type: 'single',
            question: 'x² + 4x + 4 = 0 теңдеуі қандай түбірлерге ие?',
            options: ['Екі әртүрлі түбір', 'Қос түбір', 'Түбір жоқ', 'Бір түбір'],
            correctAnswer: 'Қос түбір',
            explanation: 'D = 16 - 16 = 0, қос түбір x = -2',
            points: 1,
          },
        ],
      },
      {
        id: 'square-roots',
        title: 'Квадрат түбір',
        description: 'Квадрат түбірмен амалдар',
        questions: [
          {
            id: '8-sqrt-1',
            type: 'single',
            question: '√144 мәнін табыңыз',
            options: ['11', '12', '13', '14'],
            correctAnswer: '12',
            explanation: '√144 = 12, себебі 12² = 144',
            points: 1,
          },
          {
            id: '8-sqrt-2',
            type: 'input',
            question: '√50 өрнегін жеңілдетіңіз: a√2 түрінде, a-ны жазыңыз',
            correctAnswer: '5',
            explanation: '√50 = √(25×2) = 5√2',
            points: 2,
          },
        ],
      },
      {
        id: 'pythagorean',
        title: 'Пифагор теоремасы',
        description: 'Тікбұрышты үшбұрыш',
        questions: [
          {
            id: '8-pyth-1',
            type: 'single',
            question: 'Катеттері 3 және 4 болатын тікбұрышты үшбұрыштың гипотенузасы неге тең?',
            options: ['5', '6', '7', '√7'],
            correctAnswer: '5',
            explanation: 'c² = 3² + 4² = 9 + 16 = 25, c = 5',
            points: 1,
          },
          {
            id: '8-pyth-2',
            type: 'input',
            question: 'Гипотенузасы 13, бір катеті 5 болса, екінші катет неге тең?',
            correctAnswer: '12',
            explanation: 'b² = 13² - 5² = 169 - 25 = 144, b = 12',
            points: 2,
          },
        ],
      },
    ],
  },
  9: {
    id: 9,
    label: '9 сынып',
    topics: [
      {
        id: 'quadratic-function',
        title: 'Квадраттық функция',
        description: 'Парабола және оның қасиеттері',
        questions: [
          {
            id: '9-qfunc-1',
            type: 'single',
            question: 'y = x² - 4x + 3 параболасының төбесінің x координатасы қандай?',
            options: ['1', '2', '3', '4'],
            correctAnswer: '2',
            explanation: 'x₀ = -b/(2a) = 4/2 = 2',
            points: 1,
          },
          {
            id: '9-qfunc-2',
            type: 'multiple',
            question: 'y = -x² + 4 функциясы үшін дұрыс тұжырымдарды таңдаңыз',
            options: [
              'Тармақтары жоғары бағытталған',
              'Тармақтары төмен бағытталған',
              'Төбесі (0, 4) нүктесінде',
              'x осімен қиылыспайды',
            ],
            correctAnswer: ['Тармақтары төмен бағытталған', 'Төбесі (0, 4) нүктесінде'],
            explanation: 'a < 0, тармақтары төмен; төбе (0, 4)',
            points: 2,
          },
        ],
      },
      {
        id: 'progressions',
        title: 'Прогрессиялар',
        description: 'Арифметикалық және геометриялық прогрессиялар',
        questions: [
          {
            id: '9-prog-1',
            type: 'single',
            question: 'Арифметикалық прогрессияда a₁ = 3, d = 2. a₅ неге тең?',
            options: ['9', '10', '11', '12'],
            correctAnswer: '11',
            explanation: 'a₅ = a₁ + 4d = 3 + 8 = 11',
            points: 1,
          },
          {
            id: '9-prog-2',
            type: 'input',
            question: 'Геометриялық прогрессияда b₁ = 2, q = 3. b₄ неге тең?',
            correctAnswer: '54',
            explanation: 'b₄ = b₁ × q³ = 2 × 27 = 54',
            points: 2,
          },
        ],
      },
      {
        id: 'trigonometry-basics',
        title: 'Тригонометрия негіздері',
        description: 'sin, cos, tan функциялары',
        questions: [
          {
            id: '9-trig-1',
            type: 'single',
            question: 'sin 30° мәні қандай?',
            options: ['1/2', '√2/2', '√3/2', '1'],
            correctAnswer: '1/2',
            explanation: 'sin 30° = 1/2',
            points: 1,
          },
          {
            id: '9-trig-2',
            type: 'single',
            question: 'cos 60° мәні қандай?',
            options: ['1/2', '√2/2', '√3/2', '0'],
            correctAnswer: '1/2',
            explanation: 'cos 60° = 1/2',
            points: 1,
          },
        ],
      },
    ],
  },
  10: {
    id: 10,
    label: '10 сынып',
    topics: [
      {
        id: 'trigonometric-equations',
        title: 'Тригонометриялық теңдеулер',
        description: 'Тригонометриялық теңдеулерді шешу',
        questions: [
          {
            id: '10-trieq-1',
            type: 'single',
            question: 'sin x = 1/2 теңдеуінің [0; 2π] аралығындағы шешімдер саны',
            options: ['1', '2', '3', '4'],
            correctAnswer: '2',
            explanation: 'x = π/6 және x = 5π/6',
            points: 1,
          },
          {
            id: '10-trieq-2',
            type: 'input',
            question: 'cos x = 0 теңдеуінің ең кіші оң шешімі (градуспен)',
            correctAnswer: '90',
            explanation: 'cos 90° = 0',
            points: 2,
          },
        ],
      },
      {
        id: 'derivatives',
        title: 'Туынды',
        description: 'Туынды табу ережелері',
        questions: [
          {
            id: '10-der-1',
            type: 'single',
            question: 'f(x) = x³ функциясының туындысы f\'(x) қандай?',
            options: ['3x', '3x²', 'x²', '3x³'],
            correctAnswer: '3x²',
            explanation: '(xⁿ)\' = n·xⁿ⁻¹, демек (x³)\' = 3x²',
            points: 1,
          },
          {
            id: '10-der-2',
            type: 'single',
            question: 'f(x) = 5x² + 3x - 2 функциясында f\'(1) неге тең?',
            options: ['10', '11', '12', '13'],
            correctAnswer: '13',
            explanation: 'f\'(x) = 10x + 3, f\'(1) = 10 + 3 = 13',
            points: 1,
          },
          {
            id: '10-der-3',
            type: 'input',
            question: 'f(x) = x⁴ функциясында f\'(2) неге тең?',
            correctAnswer: '32',
            explanation: 'f\'(x) = 4x³, f\'(2) = 4 × 8 = 32',
            points: 2,
          },
        ],
      },
      {
        id: 'logarithms',
        title: 'Логарифмдер',
        description: 'Логарифм қасиеттері',
        questions: [
          {
            id: '10-log-1',
            type: 'single',
            question: 'log₂ 8 мәні қандай?',
            options: ['2', '3', '4', '8'],
            correctAnswer: '3',
            explanation: '2³ = 8, демек log₂ 8 = 3',
            points: 1,
          },
          {
            id: '10-log-2',
            type: 'input',
            question: 'lg 100 мәнін табыңыз (lg — ондық логарифм)',
            correctAnswer: '2',
            explanation: '10² = 100, демек lg 100 = 2',
            points: 2,
          },
        ],
      },
    ],
  },
  11: {
    id: 11,
    label: '11 сынып',
    topics: [
      {
        id: 'integrals',
        title: 'Интегралдар',
        description: 'Анықталмаған және анықталған интегралдар',
        questions: [
          {
            id: '11-int-1',
            type: 'single',
            question: '∫ 2x dx интегралы қандай?',
            options: ['x² + C', '2x² + C', 'x + C', '2 + C'],
            correctAnswer: 'x² + C',
            explanation: '∫ 2x dx = x² + C',
            points: 1,
          },
          {
            id: '11-int-2',
            type: 'single',
            question: '∫₀² x dx анықталған интегралының мәні қандай?',
            options: ['1', '2', '3', '4'],
            correctAnswer: '2',
            explanation: '[x²/2]₀² = 4/2 - 0 = 2',
            points: 1,
          },
          {
            id: '11-int-3',
            type: 'input',
            question: '∫₁³ 2 dx интегралының мәнін табыңыз',
            correctAnswer: '4',
            explanation: '∫₁³ 2 dx = 2x|₁³ = 6 - 2 = 4',
            points: 2,
          },
        ],
      },
      {
        id: 'probability',
        title: 'Ықтималдық',
        description: 'Ықтималдық теориясы негіздері',
        questions: [
          {
            id: '11-prob-1',
            type: 'single',
            question: 'Сүйек лақтырғанда 6 түсу ықтималдығы қандай?',
            options: ['1/2', '1/3', '1/6', '1/12'],
            correctAnswer: '1/6',
            explanation: 'P = 1/6 (6 жақтан біреуі)',
            points: 1,
          },
          {
            id: '11-prob-2',
            type: 'input',
            question: 'Екі сүйек лақтырғанда қосынды 7 болу ықтималдығы қандай? (бөлшек түрінде, мысалы: 1/6)',
            correctAnswer: '1/6',
            explanation: 'Қолайлы нұсқалар: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6, жалпы 36, P = 6/36 = 1/6',
            points: 2,
          },
        ],
      },
      {
        id: 'complex-numbers',
        title: 'Комплекс сандар',
        description: 'Комплекс сандармен амалдар',
        questions: [
          {
            id: '11-comp-1',
            type: 'single',
            question: 'i² неге тең? (i — жорамал бірлік)',
            options: ['1', '-1', 'i', '-i'],
            correctAnswer: '-1',
            explanation: 'i² = -1 (анықтама бойынша)',
            points: 1,
          },
          {
            id: '11-comp-2',
            type: 'single',
            question: '(2 + 3i) + (4 - i) қосындысын табыңыз',
            options: ['6 + 2i', '6 + 4i', '6 - 2i', '2 + 2i'],
            correctAnswer: '6 + 2i',
            explanation: '(2+4) + (3-1)i = 6 + 2i',
            points: 1,
          },
        ],
      },
    ],
  },
}

export const gradeList = Object.values(courseData).map((grade) => ({
  id: grade.id,
  label: grade.label,
  topicCount: grade.topics.length,
}))
